modmap:
  - name: PushToTalk
    remap:
      CapsLock: F13
      KEY_INSERT: PROG1
  - name: Global
    remap:
      e: f
      r: p
      t: g
      y: j
      u: l
      i: u
      o: y
      p: KEY_SEMICOLON

      s: r
      d: s
      f: t
      g: d
      j: n
      k: e
      l: i
      KEY_SEMICOLON: o
      n: k
    #device:
      #only: ['SteelSeries SteelSeries Apex 3 TKL', 'DualSense Wireless Controller']
    application: # "wmctrl -x -l" on X11 or "niri msg windows" on Niri
      not: [
        steam_app_2231380.steam_app_2231380, # Ghost Recon Breakpoint
        steam_app_2231380, # Ghost Recon Breakpoint
        grb_vulkan.exe, # Ghost Recon Breakpoint
        grb.exe, # Ghost Recon Breakpoint
        steam_app_553850, # Helldivers 2
        helldivers2.exe, # Helldivers 2
        elitedangerous64.exe, # Elite Dangerous
        steam_app_359320, # Elite Dangerous
        steam_app_359320.steam_app_359320, # Elite Dangerous
        steam_app_275850, # No Man's Sky
      ]
